<?php

/**
 * @file
 * Contains date_condition.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function date_condition_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the date_condition module.
    case 'help.page.date_condition':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Data_condition plugin') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function date_condition_theme() {
  return [
    'date_condition' => [
      'render element' => 'children',
    ],
  ];
}
